# Generated by Django 4.1.7 on 2023-02-17 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeItem', '0002_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
