# Generated by Django 4.1.7 on 2023-02-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeItem', '0004_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
